#
#
#  spring:
#  datasource:
#   url: jdbc:mysql://localhost:3306/bankkk
#   driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate.ddl-auto: update
#    hibernate.database:
#    generate-ddl: true
#    show-sql: true





spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/bankkk
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect


